FROM alpine:latest

# Install required packages
RUN apk add --no-cache mysql-client aws-cli bash

# Copy import script
COPY db-import-full.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/db-import-full.sh

CMD ["/usr/local/bin/db-import-full.sh"]