version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      # Store logs outside of volume to persist them
      - drupal_logs:/var/log/apache2
    depends_on:
      - db
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: juliush761
      DRUPAL_DB_USER: drupal7
      DRUPAL_DB_PASSWORD: drupal7
      PHP_MEMORY_LIMIT: 256M
      PHP_MAX_EXECUTION_TIME: 120

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - drupal_db:/var/lib/mysql
      - ./database/juliush761_mysql_db.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    environment:
      MYSQL_DATABASE: juliush761
      MYSQL_USER: drupal7
      MYSQL_PASSWORD: drupal7
      MYSQL_ROOT_PASSWORD: root_password
    command: --innodb_use_native_aio=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode="ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root_password
    depends_on:
      - db

volumes:
  drupal_db:
  drupal_logs:
