AWSTemplateFormatVersion: '2010-09-09'
Description: 'Julius Wirth ElastiCache Redis Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: 'production'
    AllowedValues: ['development', 'staging', 'production']
    Description: Environment name
  
  ProjectName:
    Type: String
    Default: 'julius-wirth'
    Description: Project name for resource tagging

  CacheNodeType:
    Type: String
    Default: 'cache.t3.micro'
    AllowedValues: ['cache.t3.micro', 'cache.t3.small', 'cache.t3.medium']
    Description: ElastiCache node type

  NumCacheNodes:
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 3
    Description: Number of cache nodes

Resources:
  # Security Group for ElastiCache
  CacheSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Julius Wirth ElastiCache Redis
      VpcId: 
        Fn::ImportValue: !Sub '${ProjectName}-vpc-id-${Environment}'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: 
            Fn::ImportValue: !Sub '${ProjectName}-web-sg-id-${Environment}'
          Description: Allow Redis access from web servers
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-cache-sg-${Environment}'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # ElastiCache Parameter Group for Redis optimization
  CacheParameterGroup:
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      CacheParameterGroupFamily: redis6.x
      Description: Parameter group for Julius Wirth Redis
      Properties:
        maxmemory-policy: allkeys-lru
        timeout: 300
        tcp-keepalive: 60

  # ElastiCache Redis Cluster
  RedisCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      ClusterName: !Sub '${ProjectName}-redis-${Environment}'
      Engine: redis
      EngineVersion: '6.2'
      CacheNodeType: !Ref CacheNodeType
      NumCacheNodes: !Ref NumCacheNodes
      Port: 6379
      
      # Network Configuration
      CacheSubnetGroupName: 
        Fn::ImportValue: !Sub '${ProjectName}-cache-subnet-group-${Environment}'
      VpcSecurityGroupIds:
        - !Ref CacheSecurityGroup
      
      # Parameter Group
      CacheParameterGroupName: !Ref CacheParameterGroup
      
      # Availability Zone Configuration
      AZMode: single-az
      PreferredAvailabilityZone: eu-south-1a
      
      # Backup Configuration
      SnapshotRetentionLimit: 1
      SnapshotWindow: '03:00-05:00'
      PreferredMaintenanceWindow: 'sun:05:00-sun:06:00'
      
      # Notifications
      NotificationTopicArn: !Ref CacheAlarmTopic
      
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-redis-${Environment}'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: 'Drupal Cache'

  # CloudWatch Alarms for Cache Monitoring
  CacheCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: ElastiCache high CPU utilization
      AlarmActions:
        - !Ref CacheAlarmTopic
      MetricName: CPUUtilization
      Namespace: AWS/ElastiCache
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: CacheClusterId
          Value: !Ref RedisCluster

  CacheMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: ElastiCache high memory utilization
      AlarmActions:
        - !Ref CacheAlarmTopic
      MetricName: DatabaseMemoryUsagePercentage
      Namespace: AWS/ElastiCache
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 85
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: CacheClusterId
          Value: !Ref RedisCluster

  CacheConnectionsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: ElastiCache high connection count
      AlarmActions:
        - !Ref CacheAlarmTopic
      MetricName: CurrConnections
      Namespace: AWS/ElastiCache
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 50
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: CacheClusterId
          Value: !Ref RedisCluster

  # SNS Topic for Cache Alarms
  CacheAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-cache-alarms-${Environment}'
      DisplayName: Julius Wirth Cache Alarms

Outputs:
  RedisEndpoint:
    Description: Redis cluster endpoint
    Value: !GetAtt RedisCluster.RedisEndpoint.Address
    Export:
      Name: !Sub '${ProjectName}-redis-endpoint-${Environment}'

  RedisPort:
    Description: Redis cluster port
    Value: !GetAtt RedisCluster.RedisEndpoint.Port
    Export:
      Name: !Sub '${ProjectName}-redis-port-${Environment}'

  CacheSecurityGroupId:
    Description: Cache security group ID
    Value: !Ref CacheSecurityGroup
    Export:
      Name: !Sub '${ProjectName}-cache-sg-id-${Environment}'

  CacheAlarmTopicArn:
    Description: SNS topic for cache alarms
    Value: !Ref CacheAlarmTopic
    Export:
      Name: !Sub '${ProjectName}-cache-alarm-topic-${Environment}'