AWSTemplateFormatVersion: '2010-09-09'
Description: 'Julius Wirth S3 Storage Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: 'production'
    AllowedValues: ['development', 'staging', 'production']
    Description: Environment name
  
  ProjectName:
    Type: String
    Default: 'julius-wirth'
    Description: Project name for resource tagging

Resources:
  # S3 Bucket for Public Files (Drupal files directory)
  PublicFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-public-files-${Environment}-${AWS::AccountId}'
      AccessControl: PublicRead
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, HEAD]
            AllowedOrigins: ['*']
            MaxAge: 3600
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-public-files-${Environment}'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: 'Drupal Public Files'

  # S3 Bucket Policy for Public Files
  PublicFilesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PublicFilesBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${PublicFilesBucket}/*'
          - Sid: CloudFrontOriginAccess
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}'
            Action: 's3:GetObject'
            Resource: !Sub '${PublicFilesBucket}/*'

  # S3 Bucket for Private Files
  PrivateFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-private-files-${Environment}-${AWS::AccountId}'
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 180
                StorageClass: GLACIER
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      ServerSideEncryptionConfiguration:
        Rules:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-private-files-${Environment}'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: 'Drupal Private Files'

  # S3 Bucket for Backups
  BackupsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-backups-${Environment}-${AWS::AccountId}'
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldBackups
            Status: Enabled
            ExpirationInDays: 90
          - Id: TransitionBackups
            Status: Enabled
            Transitions:
              - TransitionInDays: 7
                StorageClass: STANDARD_IA
              - TransitionInDays: 30
                StorageClass: GLACIER
              - TransitionInDays: 60
                StorageClass: DEEP_ARCHIVE
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      ServerSideEncryptionConfiguration:
        Rules:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-backups-${Environment}'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: 'Database and Application Backups'

  # S3 Bucket for Deployments
  DeploymentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-deployments-${Environment}-${AWS::AccountId}'
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldDeployments
            Status: Enabled
            ExpirationInDays: 30
          - Id: TransitionDeployments
            Status: Enabled
            Transitions:
              - TransitionInDays: 7
                StorageClass: STANDARD_IA
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      ServerSideEncryptionConfiguration:
        Rules:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-deployments-${Environment}'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: 'Application Deployment Artifacts'

  # CloudFront Origin Access Identity
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'OAI for ${ProjectName} ${Environment}'

  # CloudWatch Alarms for S3 Monitoring
  PublicFilesBucketSizeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Public files bucket size alarm
      AlarmActions:
        - !Ref StorageAlarmTopic
      MetricName: BucketSizeBytes
      Namespace: AWS/S3
      Statistic: Average
      Period: 86400  # Daily
      EvaluationPeriods: 1
      Threshold: 5368709120  # 5GB in bytes
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: BucketName
          Value: !Ref PublicFilesBucket
        - Name: StorageType
          Value: StandardStorage

  # SNS Topic for Storage Alarms
  StorageAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-storage-alarms-${Environment}'
      DisplayName: Julius Wirth Storage Alarms

Outputs:
  PublicFilesBucketName:
    Description: Public files S3 bucket name
    Value: !Ref PublicFilesBucket
    Export:
      Name: !Sub '${ProjectName}-public-bucket-${Environment}'

  PublicFilesBucketDomainName:
    Description: Public files S3 bucket domain name
    Value: !GetAtt PublicFilesBucket.DomainName
    Export:
      Name: !Sub '${ProjectName}-public-bucket-domain-${Environment}'

  PrivateFilesBucketName:
    Description: Private files S3 bucket name
    Value: !Ref PrivateFilesBucket
    Export:
      Name: !Sub '${ProjectName}-private-bucket-${Environment}'

  BackupsBucketName:
    Description: Backups S3 bucket name
    Value: !Ref BackupsBucket
    Export:
      Name: !Sub '${ProjectName}-backups-bucket-${Environment}'

  DeploymentsBucketName:
    Description: Deployments S3 bucket name
    Value: !Ref DeploymentsBucket
    Export:
      Name: !Sub '${ProjectName}-deployments-bucket-${Environment}'

  CloudFrontOriginAccessIdentityId:
    Description: CloudFront Origin Access Identity ID
    Value: !Ref CloudFrontOriginAccessIdentity
    Export:
      Name: !Sub '${ProjectName}-oai-id-${Environment}'

  StorageAlarmTopicArn:
    Description: SNS topic for storage alarms
    Value: !Ref StorageAlarmTopic
    Export:
      Name: !Sub '${ProjectName}-storage-alarm-topic-${Environment}'